apiVersion: v1
kind: Service
metadata:
  name: {{ include "nornir.fullname" . }}-gateway
spec:
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.port }}
  selector:
    app: {{ include "nornir.fullname" . }}-gateway
