// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: workflowpb/workflow.proto

package workflowpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to start a workflow
type StartWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowRequest) Reset() {
	*x = StartWorkflowRequest{}
	mi := &file_workflowpb_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowRequest) ProtoMessage() {}

func (x *StartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflowpb_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflowpb_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *StartWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response after starting a workflow
type StartWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowResponse) Reset() {
	*x = StartWorkflowResponse{}
	mi := &file_workflowpb_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowResponse) ProtoMessage() {}

func (x *StartWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflowpb_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StartWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflowpb_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *StartWorkflowResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartWorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Request to check workflow status
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_workflowpb_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflowpb_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_workflowpb_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response with workflow status
type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_workflowpb_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflowpb_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_workflowpb_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_workflowpb_workflow_proto protoreflect.FileDescriptor

const file_workflowpb_workflow_proto_rawDesc = "" +
	"\n" +
	"\x19workflowpb/workflow.proto\x12\bworkflow\"*\n" +
	"\x14StartWorkflowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"?\n" +
	"\x15StartWorkflowResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\"\n" +
	"\x10GetStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x11GetStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xa9\x01\n" +
	"\x0fWorkflowService\x12P\n" +
	"\rStartWorkflow\x12\x1e.workflow.StartWorkflowRequest\x1a\x1f.workflow.StartWorkflowResponse\x12D\n" +
	"\tGetStatus\x12\x1a.workflow.GetStatusRequest\x1a\x1b.workflow.GetStatusResponseB9Z7github.com/erikkvale/nornir/proto/workflowpb;workflowpbb\x06proto3"

var (
	file_workflowpb_workflow_proto_rawDescOnce sync.Once
	file_workflowpb_workflow_proto_rawDescData []byte
)

func file_workflowpb_workflow_proto_rawDescGZIP() []byte {
	file_workflowpb_workflow_proto_rawDescOnce.Do(func() {
		file_workflowpb_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflowpb_workflow_proto_rawDesc), len(file_workflowpb_workflow_proto_rawDesc)))
	})
	return file_workflowpb_workflow_proto_rawDescData
}

var file_workflowpb_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_workflowpb_workflow_proto_goTypes = []any{
	(*StartWorkflowRequest)(nil),  // 0: workflow.StartWorkflowRequest
	(*StartWorkflowResponse)(nil), // 1: workflow.StartWorkflowResponse
	(*GetStatusRequest)(nil),      // 2: workflow.GetStatusRequest
	(*GetStatusResponse)(nil),     // 3: workflow.GetStatusResponse
}
var file_workflowpb_workflow_proto_depIdxs = []int32{
	0, // 0: workflow.WorkflowService.StartWorkflow:input_type -> workflow.StartWorkflowRequest
	2, // 1: workflow.WorkflowService.GetStatus:input_type -> workflow.GetStatusRequest
	1, // 2: workflow.WorkflowService.StartWorkflow:output_type -> workflow.StartWorkflowResponse
	3, // 3: workflow.WorkflowService.GetStatus:output_type -> workflow.GetStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workflowpb_workflow_proto_init() }
func file_workflowpb_workflow_proto_init() {
	if File_workflowpb_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflowpb_workflow_proto_rawDesc), len(file_workflowpb_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflowpb_workflow_proto_goTypes,
		DependencyIndexes: file_workflowpb_workflow_proto_depIdxs,
		MessageInfos:      file_workflowpb_workflow_proto_msgTypes,
	}.Build()
	File_workflowpb_workflow_proto = out.File
	file_workflowpb_workflow_proto_goTypes = nil
	file_workflowpb_workflow_proto_depIdxs = nil
}
